export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_SUCCESS = 'STAFFS_SUCCESS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const DEPARTMENTS_SUCCESS = 'DEPARTMENTS_SUCCESS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';